---
title: "Workshop1_Dataviz_in_R"
author: "Jacqueline Hintz"
date: "`r Sys.Date()`"
output: html_document
---
###Loading packages

First you will need to install the tidyverse. Make sure you run this in R console. You may have to update your R. 

```r 
install.packages("tidyverse")
library(tidyverse)
```

The mpg data frame in ggplot2 is a dataset with observations (234 rows of data) and variables (in the columns). 

##Creating first ggplot
To create the first plot of this dataset. Using ggplot2, you can plot the data (data = mpg) and then put the size of the engine (displ) on the x axis and the fuel efficiency (hwy) on the y axis. 

```r
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

##Understaning the grammar of graphics

#Graphing Template

```r
`ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))
 ```


```r
`ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, colour = class))
```
- note mapped color to class

now change point sizes
```r
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```
#> Warning: Using size for a discrete variable is not advised. 

change point transparency.
```r
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```
chnage point shape by class

```r 
`ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```
  - the point end up with different shapes depending on the class
  
  You can also set these properties manually, such as by offering a number or a colour. Let’s make all of our points blue
  
```r 
`ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```
  
  
## Facet and panel plots
This allows you to develop separate plots for a range of reasons, most often to show a subset of your data. In ggplot2, you’ll typically do this using facets.


only use facet_wrap() for discrete variable



```r 
`ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
  ```

If you want to do this with more than one variable, then use facet_grid(). Here you need two variables using ~ to split them up.

Facet plot on the combination of two variables using facet_grid(). Facet grid needs two variables separated by a ~.

```r
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
```
Use a . if you do not want to facet in the rows or column dimension. Note what happens in this case: this squishes them together
```r
ggplot(data = mpg) + 
+     geom_point(mapping = aes(x = displ, y = hwy)) + 
+     facet_grid(. ~ cyl)
```
### Fitting simple lines

An outstanding feature of ggplot2 is that you can use a variety of visual objects to represent your data. So far we have used points that are plotted at the coordinate location of the x and y axes for each data point.

To display data as points, use geom_point().
```r 
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
  ```
To display the same data as a smooth line fit through the points use geom_smooth().
```r
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy))
  ```
  
GEOM: A geom is an object that your plot uses to represent the data. To change the geom type in your plot, simply change the geom function that you add to your plot template. Sometimes you may want to try a few things out, in which case you could use comments to help you remember what worked and what didn’t.

```r
ggplot(data = mpg) +
+ geom_smooth(mapping = aes(x = displ, y = hwy))
```

Can also change line type
```r 
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
  ```
set the group aesthetic to a categorical variable to draw multiple objects

```r 
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
  ```
  change color of each line based on drv value

```r
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE,
  )
  ```
  
Plotting mulitple geoms on a single plot. just add them together. This one is nice for showing the underlying data and how it relates to the geom_smooth line.

```r
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
  ```
  exact same plot but progamm more efficient
```r
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()
  ```
note the layers , this one is noted by class
```r
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth()
  ```
The same goes if you want to specify different data for each layer. Here, we use a filter (class = "subcompact") to select a subset of the data and plot only that subset.

```r
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)

```
### Transformations and STATS
We are going to learn about easy transformations and data summaries using another dataset provided in ggplot2, specifically to support the teaching of transformations.  The diamonds dataset comes in ggplot2 and contains information about ~54,000 diamonds, including the price, carat, color, clarity, and cut of each diamond.

Our first bar chart shows that more diamonds are available with high quality cuts than low quality cuts

```r
ggplot(data = diamonds) + 
  geom_bar(mapping = aes( x = cut))

```
You can generally use geoms and stats interchangeably. For example, you can recreate the previous plot using stat_count() instead of geom_bar()

```r
ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))
  ```
Can override a default mapping fro transformed variables to aesthetics. For instance, you could display a bar chart of the proportion of your total diamond dataset rather than a count.

```r
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = stat(prop), group = 1))
```
stat_summary() -> to show alittle more about these transformations in the plot

##Aesthetic adjustments
Another way to boost the way you can convey information with plots using ggplot2 is to use aesthetics like colour or fill to change aspects of bar colours.

```r
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))
  ```
Now try using these aesthetics to colour by another variable like clarity. Notice how the stacking is done automatically. This is done behind the scenes with a position argument.

```r
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity))
  ```
  
The ability to make position adjustments is vital, it allows you to customise your plots in three ways, identity (raw data), fill (changes heights) and dodge (which forces ggplot2 to not put things on top of each other)

If you use position = "identity", you will be able to place each object exactly where it falls in the context of the graph. This is vital for point charts like scatter plots but makes a mess in a bar plot situation by showing too much information (a bar plot generally summarises information). So in this case we will need to alter the bar aesthetic.

```r
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")

#To color the bar outlines with no fill color
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity") 
```

  
position = "fill" works like stacking, but makes each set of stacked bars the same height. below
code
```r

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

```
position = "dodge" places overlapping objects directly beside one another.

```r
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")
  ```
 bonus position adjustment is jitter, which slightly moves points so you can see them all (especially when they overlap). I’m sure you’ve seen really nice box plots with jittered points all over them, which you handle with this function.
position = "jitter" adds a small amount of random noise to each point to avoid overplotting when points overlap. This is useful for scatterplots but not barplots.

```r
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")
  ```
  
RECAP: skeleton code of ggplot

```r
ggplot(data = <DATA>) + 
  <GEOM_FUNCTION>(
     mapping = aes(<MAPPINGS>),
     stat = <STAT>, 
     position = <POSITION>
  ) +
  <FACET_FUNCTION>

```
### ASSIGNEMENT: Plot Deconstruction

stuff i found wrong in the plot
could combine them and make them different colors

extraxt data using website
saved as csvs
copied csv in excel then tidyied in excel
then upload in R 
Bar


  
  
  






